### ISSUE TITLE
error: When trying to compute drift in a umbrella chart

### ISSUE THREAD

**Issue by ishnmu** [nikhilsbhat/helm-drift#29]
We deploy our services using helm umbrella chart (one chart has many within it), while attempting to calculate drift in config, the plugin is panicking. 

error:
```
{"level":"debug","msg":"rendering manifest to disc, hold on for a moment....","time":"2024-09-27T15:59:25+05:30"}
{"level":"debug","msg":"failed to get 'metadata' from the manifest","time":"2024-09-27T15:59:25+05:30"}
ERRO[0003] getting manifest information from template errored with 'failed to get kind from the manifest, 'kind' is not type string' 
{"level":"fatal","msg":"failed to get kind from the manifest, 'kind' is not type string","time":"2024-09-27T15:59:25+05:30"}
Error: plugin "drift" exited with error
```

**Comment by nikhilsbhat** [comment]
@ishnmu, It seems I know the issue. I already have a PR open for another Helm plugin I developed [ref](https://github.com/nikhilsbhat/helm-images/pull/42). I'll work on abstracting the solution so that both plugins benefit from it. Were there any specific charts you tested with? That would help me troubleshoot further.

**Comment by ishnmu** [comment]
Nikhil, thanks for the response.

I cant share the details of the umbrella chart I used as its internal. But
let me see if I can reproduce it with the dummy umbrella chart mimicking
the actual structure.
